version: '3.8'
services:
  nest-api:
    container_name: nest-api-nexo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads

  postgres:
    image: postgres:15
    container_name: postgres-nexo
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db-nexo
  uploads:
    name: nest-uploads
